-- Generated by Names Studio. Prefer editing via the app.

local data_cfg = {
	towns = {
		["kust"] = {
			"Den Helder", "Egmond aan Zee", "Zandvoort", "Katwijk", "Noordwijk", "Scheveningen",
			"Hoek van Holland", "Vlissingen", "Westkapelle", "Domburg", "Renesse", "Ouddorp",
			"Callantsoog", "Bergen aan Zee", "Petten", "Wijk aan Zee", "Cadzand", "Breskens",
			"Zoutelande", "Burgh-Haamstede", "Harlingen", "Zierikzee", "Hellevoetsluis", "Brielle",
			"Oostvoorne", "Rockanje", "Kijkduin", "Camperduin", "Julianadorp", "Terschelling",
			"Vlieland", "Ameland", "Schiermonnikoog", "Texel", "De Koog", "Oudeschild",
			"Den Burg", "Sint Maartenszee", "Zwanenwater", "Nieuwvliet", "Ellewoutsdijk", "Veere",
			"Colijnsplaat", "Kamperland", "Vrouwenpolder", "Oostkapelle", "Haamstede", "Scharendijke",
			"Stellendam", "Goedereede", "Wassenaar", "Monster", "Ter Heijde", "Zandmotor",
			"Oost-Vlieland", "Hollum", "Nes", "Ballum",
		},
		["rivier"] = {
			"Zaltbommel", "Tiel", "Culemborg", "Wijk bij Duurstede", "Rhenen", "Wageningen",
			"Zutphen", "Deventer", "Kampen", "Gorinchem", "Woudrichem", "Nijmegen",
			"Venlo", "Roermond", "Maastricht", "Thorn", "Gennep", "Cuijk",
			"Grave", "Ravenstein", "Megen", "Vianen", "Schoonhoven", "Lobith",
			"Millingen aan de Rijn", "Doesburg", "Hattem", "Vreeswijk", "Heusden", "Arnhem",
			"Dieren", "Rheden", "Brummen", "Eefde", "Olst", "Wijhe",
			"Zwolle", "Hasselt", "Genemuiden", "Zwartsluis", "Hedel", "Ammerzoden",
			"Poederoijen", "Brakel", "Rossum", "Kerkdriel", "Alphen aan den Rijn", "Woerden",
			"Oudewater", "Montfoort", "Lopik", "Nieuwpoort", "Ameide", "Lexmond",
			"Everdingen", "Beusichem", "Opheusden", "Heteren", "Driel", "Elst",
			"Bemmel", "Lent", "Huissen", "Zevenaar", "Pannerden", "Angeren",
			"Ewijk", "Winssen", "Beuningen", "Wychen", "Mook", "Middelaar",
			"Well", "Arcen", "Baarlo", "Buggenum", "Kessel", "Herten",
			"Echt", "Stein", "Born", "Obbicht", "Elsloo", "Borgharen",
			"Itteren", "Sint Pieter", "Wijlre",
		},
		["heuvel"] = {
			"Valkenburg", "Epen", "Gulpen", "Berg en Dal", "Beek", "Ubbergen",
			"Amerongen", "Doorn", "Driebergen", "Zeist", "Otterlo", "Hoenderloo",
			"Slenaken", "Vaals", "Wijlre", "Mechelen", "Cadier en Keer", "Margraten",
			"Eys", "Wittem", "Bemelen", "Berg en Terblijt", "Schin op Geul", "Houthem",
			"Meerssen", "Simpelveld", "Bocholtz", "Gronsveld", "Cottessen", "Camerig",
			"Mamelis", "Terziet", "Vijlen", "Ingber", "Mesch", "Noorbeek",
			"Eijsden", "Sint Geertruid", "Heythuysen", "Cuijk", "Rhenen", "Leersum",
			"Maarn", "Maarsbergen", "Austerlitz", "Woudenberg", "Renkum", "Oosterbeek",
			"Wolfheze", "Heelsum", "Ede", "Bennekom", "Lunteren", "Garderen",
			"Uddel", "Elspeet", "Harskamp", "Kootwijk", "Hoog Soeren", "Beekbergen",
			"Loenen", "Eerbeek", "Terlet", "Rozendaal", "Velp", "Ellecom",
		},
		["industrie"] = {
			"Zaandam", "Geleen", "Sittard", "Terneuzen", "Vlaardingen", "Delfzijl",
			"Hengelo", "Helmond", "Oss", "Veenendaal", "IJmuiden", "Botlek",
			"Pernis", "Moerdijk", "Sluiskil", "Almelo", "Enschede", "Eindhoven",
			"Tilburg", "Weert", "Maasbracht", "Born", "Beek", "Stein",
			"Chemelot", "Europoort", "Maasvlakte", "Rozenburg", "Schiedam", "Maassluis",
			"Krimpen aan den IJssel", "Capelle aan den IJssel", "Papendrecht", "Hardinxveld-Giessendam", "Zwijndrecht", "Hendrik-Ido-Ambacht",
			"Krommenie", "Wormerveer", "Assendelft", "Koog aan de Zaan", "Zaandijk", "Westzaan",
			"Beverwijk", "Velsen", "Santpoort", "Uithoorn", "Weesp", "Vianen",
			"Culemborg", "Nijverdal", "Goor", "Rijssen", "Oldenzaal", "Borne",
			"Delden", "Ulft", "Terborg", "Winterswijk", "Doetinchem", "Gendringen",
			"Oud-Gastel", "Roosendaal", "Bergen op Zoom", "Steenbergen", "Halsteren",
		},
		["hout"] = {
			"Zaagmolen", "Houtwijk", "Houthem", "Houten", "Houtrijk", "Houtigehage",
			"Boschwijk", "Zagerij", "Houtdorp", "Zaandijk", "Zaanse Schans", "Westzaan",
			"Vlist", "Haastrecht", "Bodegraven", "Zevenhuizen", "Zwammerdam", "Papendrecht",
			"Maarssen", "Eerbeek", "Apeldoorn", "Hattem", "Dieren", "Beekbergen",
			"Loenen", "Ommen", "Coevorden", "Dedemsvaart", "Balkbrug", "Lutten",
			"Hardenberg", "Gramsbergen", "Slagharen", "Vroomshoop", "Houtvester", "Boswachterij",
			"Berkenwoude", "Eikenhorst", "Beukenburg", "Dennenoord", "Lariks", "Sparrendaal",
			"Kaapse Bossen", "Staatsbosbeheer", "Houtwal", "Bosrand", "Boomkamp", "Stamdijk",
			"Plankenwijk", "Papiermolen",
		},
		["meer"] = {
			"Loosdrecht", "Vinkeveen", "Giethoorn", "Stavoren", "Lemmer", "Sloten",
			"Workum", "Hindeloopen", "Heeg", "Joure", "Medemblik", "Enkhuizen",
			"Hoorn", "Edam", "Volendam", "Monnickendam", "Marken", "Muiden",
			"Naarden", "Spakenburg", "Elburg", "Harderwijk", "Nunspeet", "Biddinghuizen",
			"Zeewolde", "Huizen", "Blaricum", "Bunschoten", "Urk", "Vollenhove",
			"Blokzijl", "Kuinre", "Oldemarkt", "Sneek", "Grou", "Terherne",
			"Langweer", "Warten", "Earnewâld", "Eernewoude", "Aalsmeer", "Kudelstaart",
			"Uithoorn", "Nieuwkoop", "Ter Aar", "Reeuwijk", "Sassenheim", "Warmond",
			"Oegstgeest", "Kaag", "Wilnis", "Nigtevecht", "Weesp", "Nederhorst den Berg",
			"Loenen", "Breukelen", "Maarssen", "Tienhoven", "Westbroek", "Spaarndam",
			"Zwanenburg", "Halfweg", "Haarlemmermeer", "Hoofddorp", "Nieuw-Vennep", "IJlst",
			"Woudsend", "Echtenerbrug", "Heerenveen", "Oranjewoud", "Gaastmeer", "Mirns",
		},
		["stad"] = {
			"Amsterdam", "Rotterdam", "Utrecht", "Den Haag", "Eindhoven", "Groningen",
			"Tilburg", "Almere", "Breda", "Nijmegen", "Apeldoorn", "Haarlem",
			"Arnhem", "Enschede", "Amersfoort", "Zaanstad", "Den Bosch", "Zwolle",
			"Leiden", "Maastricht", "Dordrecht", "Zoetermeer", "Ede", "Alkmaar",
			"Emmen", "Delft", "Deventer", "Venlo", "Leeuwarden", "Helmond",
			"Hilversum", "Heerlen", "Sittard-Geleen", "Alphen aan den Rijn", "Roosendaal", "Oss",
			"Gouda", "Lelystad", "Amstelveen", "Hoorn", "Middelburg", "Assen",
			"Hengelo", "Veenendaal", "Purmerend", "Kampen", "Doetinchem",
		},
		["landbouw"] = {
			"Zuidlaren", "Veendam", "Winschoten", "Wehe-den Hoorn", "Ezinge", "Pieterburen",
			"Warffum", "Usquert", "Uithuizen", "Loppersum", "Slochteren", "Hoogezand",
			"Muntendam", "Nieuw-Buinen", "Barger-Compascuum", "Emmer-Compascuum", "Klazienaveen", "Valthermond",
			"Exloërmond", "Stadskanaal", "Ter Apel", "Vlagtwedde", "Bellingwolde", "Heiligerlee",
			"Oude Pekela", "Nieuwe Pekela", "Wildervank", "Zuidbroek", "Sappemeer", "Oosterhesselen",
			"Dalen", "Schoonebeek", "Tubbergen", "Albergen", "Geesteren", "Ootmarsum",
			"Denekamp", "Weerselo", "Haaksbergen", "Neede", "Eibergen", "Lichtenvoorde",
			"Groenlo", "Vorden", "Hengelo Gelderland", "Hummelo", "Keijenborg", "Zelhem",
			"Hoog-Keppel", "Boerderij", "Hofstede", "Akkerdorp", "Weideland", "Graanveld",
			"Koeienbuurt", "Melkweg", "Zuivelhoek", "Appelscha", "Oosterwolde", "Marum",
			"Zevenhuizen", "Tolbert", "Leek", "Roden", "Nuis", "Peize",
		},
		["mijn"] = {
			"Heerlen", "Kerkrade", "Brunssum", "Hoensbroek", "Eygelshoven", "Nieuwenhagen",
			"Landgraaf", "Schaesberg", "Treebeek", "Merkelbeek", "Nuth", "Schinnen",
			"Spekholzerheide", "Chevremont", "Waubach", "Ubach over Worms", "Rimburg", "Bleijerheide",
			"Terwinselen", "Abdissenbosch", "Voerendaal", "Klimmen", "Ransdaal", "Heerlerbaan",
			"Mariagroeve", "Oranje-Nassau", "Emma", "Hendrik", "Wilhelmina", "Domaniale",
			"Julia", "Laura", "Maurits", "Staatsmijn", "Steenkoolberg", "Mergelgroeve",
			"Zandgroeve", "Kleigroeve", "IJzerberg", "Veldwijk", "Zandberg", "Grindgat",
			"Mergelland", "Groeve", "Delfstof", "Zandpoort", "Kleiput", "Steengroeve",
			"Steenbergen", "Cuijk",
		},
		["bos"] = {
			"Ommen", "Dwingeloo", "Havelte", "Diever", "Ruinen", "Exloo",
			"Gieten", "Hulshorst", "Vierhouten", "Putten", "Nunspeet", "Hierden",
			"Ermelo", "Speuld", "Nijkerk", "Lunteren", "Apeldoorn", "Hoog Buurlo",
			"Kootwijkerbroek", "Wekerom", "Barneveld", "Terschuur", "Hoevelaken", "Bosch en Duin",
			"Bilthoven", "Soest", "Soesterberg", "Baarn", "Lage Vuursche", "Hilversum",
			"Bussum", "Laren", "Eemnes", "Hooge Mierde", "Hilvarenbeek", "Oisterwijk",
			"Moergestel", "Dongen", "Gilze", "Rijen", "Dorst", "Ulvenhout",
			"Mastenbroek", "Heeze", "Leende", "Sterksel", "Someren", "Asten",
			"Deurne", "Helenaveen", "Ospel", "Nederweert", "Meijel", "Kessel",
			"Grashoek", "Koningslust", "Dwingelderveld", "Spier", "Westerbork", "Orvelte",
			"Zweeloo", "Schoonloo", "Gasselte", "Eext", "Anloo", "Nijlande",
			"Rolde", "Balloo", "Loon", "Zeijen", "Vries", "Taarlo",
			"Geelbroek",
		},
		["polder"] = {
			"Nagele", "Emmeloord", "Ens", "Creil", "Marknesse", "Lelystad",
			"Dronten", "Swifterbant", "Zeewolde", "Rutten", "Luttelgeest", "Kraggenburg",
			"Espel", "Tollebeek", "Bant", "Schokland", "Ketelhaven", "Almere",
			"Oostvaardersdijk", "Ridderkerk", "Barendrecht", "Zuidplas", "Nieuwerkerk aan den IJssel", "Moordrecht",
			"Gouderak", "Bleiswijk", "Berkel en Rodenrijs", "Bergschenhoek", "Zevenhuizen", "Moerkapelle",
			"Nootdorp", "Pijnacker", "Delfgauw", "Schipluiden", "Maasland", "Kwintsheul",
			"Naaldwijk", "Wateringen", "Honselersdijk", "De Lier", "Heenvliet", "Spijkenisse",
			"Hoogvliet", "Abbenbroek", "Zuidland", "Geervliet", "Oudenhoorn", "Rhoon",
			"Poortugaal", "Beemster", "Middenbeemster", "Purmerend", "Wormer", "Jisp",
			"Wijdewormer", "Zuidschermer", "Schermerhorn", "Heerhugowaard", "Broek op Langedijk", "Oudkarspel",
			"Zuid-Scharwoude", "Noord-Scharwoude", "Winkel", "Hensbroek", "Wieringerwerf", "Slootdorp",
			"Middenmeer", "Wervershoof", "Nibbixwoud",
		},
	},
	gen = {
		["kust"] = {
			["stems"] = {
				"Zand", "Duin", "Strand", "Kust", "Zee", "Wad",
				"Schelp", "Zout", "Helm", "Meeuw", "Schelde", "Noordzee",
				"Brandings", "Vuurtoren", "Mosselen",
			},
			["suffixes"] = {
				"voort", "kerke", "haven", "wijk", "dorp", "oord",
				"hoek", "gat", "duin", "sluis", "strand", "zijl",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["rivier"] = {
			["stems"] = {
				"Rijn", "Maas", "Waal", "Lek", "IJssel", "Vecht",
				"Merwe", "Linge", "Dommel", "Roer", "Amstel", "Schie",
				"Eem", "Vliet", "Overbetuwe",
			},
			["suffixes"] = {
				"dam", "brug", "veer", "waard", "oever", "poort",
				"wijk", "sluis", "ham", "voorde", "zijl", "kade",
				"dijk",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["heuvel"] = {
			["stems"] = {
				"Berg", "Heuvel", "Hoog", "Dal", "Rots", "Kalk",
				"Mergel", "Steen", "Klim", "Rade", "Kruin", "Top",
				"Hellend",
			},
			["suffixes"] = {
				"berg", "heuvel", "dal", "rade", "hoek", "top",
				"kamp", "wijk", "dorp", "hoogte", "helling",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["industrie"] = {
			["stems"] = {
				"Staal", "Fabriek", "Werk", "Machine", "Chemie", "Raffinaderij",
				"Kolen", "Schoorsteen", "Rook", "Ketel", "Smelt", "Gieterij",
				"Draad",
			},
			["suffixes"] = {
				"werk", "dorp", "oord", "haven", "stad", "wijk",
				"hoek", "kamp", "poort", "park", "terrein",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["hout"] = {
			["stems"] = {
				"Hout", "Zaag", "Plank", "Stam", "Boom", "Bos",
				"Papier", "Molen", "Timmer", "Eiken", "Beuken",
			},
			["suffixes"] = {
				"zaag", "molen", "werf", "wijk", "hoek", "dorp",
				"kamp", "hout", "markt", "loods",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["meer"] = {
			["stems"] = {
				"Meer", "Plas", "Veen", "Kaag", "Brasem", "Snoek",
				"Riet", "Lis", "Water", "Zwaan", "Fuut", "Kikker",
				"Vis", "Eend",
			},
			["suffixes"] = {
				"meer", "plas", "veen", "wijk", "dijk", "hoek",
				"oever", "dorp", "haven", "zijde", "vaart", "kolk",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["stad"] = {
			["stems"] = {},
			["suffixes"] = {},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["landbouw"] = {
			["stems"] = {
				"Akker", "Weide", "Boeren", "Koe", "Schaap", "Graan",
				"Tarwe", "Aardappel", "Melk", "Hof", "Kamp", "Es",
				"Tuin",
			},
			["suffixes"] = {
				"hof", "akker", "wei", "land", "es", "kamp",
				"dorp", "hoeve", "veld", "buurt", "kerk", "wijk",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["mijn"] = {
			["stems"] = {
				"Mijn", "Kolen", "IJzer", "Steen", "Grind", "Klei",
				"Zand", "Marmer", "Kalk", "Delf", "Schacht", "Groeve",
			},
			["suffixes"] = {
				"mijn", "hut", "berg", "groeve", "schacht", "dorp",
				"wijk", "hoek", "kuil", "gat", "terrein",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["bos"] = {
			["stems"] = {
				"Bos", "Woud", "Heide", "Eik", "Beuk", "Den",
				"Berk", "Lork", "Hout", "Zand", "Loo", "Vennen",
				"Hei", "Dennen",
			},
			["suffixes"] = {
				"bos", "woud", "loo", "heide", "veld", "hout",
				"zand", "rijk", "dorp", "hoek", "kamp", "laan",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
		["polder"] = {
			["stems"] = {
				"Polder", "Kade", "Sloot", "Wetering", "Kolk", "Boezem",
				"Molen", "Dijk", "Wiel", "Tocht", "Vaart", "Gors",
				"Slik",
			},
			["suffixes"] = {
				"polder", "kade", "hoek", "sloot", "dijk", "weg",
				"dorp", "land", "hoeve", "zijl", "kolk",
			},
			["prefixChance"] = 0.25,
			["mode"] = "both",
		},
	},
	prefixes = {
		"Oud-", "Nieuw-", "Groot-", "Klein-", "Hoog-", "Laag-",
		"Zuid-", "Noord-", "Oost-", "West-", "Boven-", "Beneden-",
		"Sint-",
	},
	streets = {
		"Dorpsstraat", "Kerkstraat", "Molenstraat", "Stationsweg", "Stationsstraat", "Hoofdstraat",
		"Schoolstraat", "Burgemeester Reigerstraat", "Julianalaan", "Beatrixlaan", "Wilhelminastraat", "Emmastraat",
		"Oranjestraat", "Prins Hendrikstraat", "Koningin Wilhelminalaan", "Marktplein", "Raadhuisplein", "Kerkplein",
		"Nieuwstraat", "Lindelaan", "Beukenlaan", "Eikenlaan", "Kastanjelaan", "Iepenlaan",
		"Populierenlaan", "Berkenlaan", "Dennenlaan", "Rozenstraat", "Tulpenstraat", "Narcissenstraat",
		"Hyacintenstraat", "Viooltjesweg", "Zonnebloemstraat", "Merelstraat", "Mezenlaan", "Spechtstraat",
		"Zwaluwstraat", "Ooievaarsweg", "Kievitslaan", "Havikstraat", "Uilenlaan", "Havenstraat",
		"Havenkade", "Kadestraat", "Singel", "Gracht", "Keizersgracht", "Prinsengracht",
		"Herengracht", "Rijnkade", "Maaskade", "Waalkade", "Veerstraat", "Veerweg",
		"Sluisstraat", "Brugstraat", "Dijkstraat", "Dijkweg", "Zeedijk", "Strandweg",
		"Duinweg", "Boulevard", "Vuurtorenweg", "Pierweg", "Kustweg", "Zandweg",
		"Polderweg", "Fabrieksstraat", "Industrieweg", "Spoorstraat", "Spoorlaan", "Fabrieksdijk",
		"Kolenstraat", "Mijnstraat", "Zaagmolenweg", "Houtstraat", "Houtwal", "Boerenweg",
		"Akkerweg", "Weidelaan", "Hofstraat", "Boomgaardlaan", "Heideweg", "Bosweg",
		"Heuvelweg", "Bergweg", "Kruisstraat", "Kruisweg", "Heerweg", "Zandpad",
		"Kerkepad", "Molenpad", "Wilhelminaplein", "Stationsplein", "Julianaplein", "Dr. Schaepmanstraat",
		"Dr. Kuyperstraat", "Burgemeester de Vlugtlaan", "Pastoor Hoeijmakersstraat", "Deken Pistoriusstraat", "Vondelstraat", "Rembrandtlaan",
		"Vermeerstraat", "Frans Halsstraat", "Van Goghlaan", "Mondriaanstraat", "Erasmuslaan", "Spinozastraat",
		"Christiaan Huygensstraat", "Willem de Zwijgerlaan", "Michiel de Ruyterstraat", "Piet Heinstraat", "Tromplaan", "Bloemenlaan",
		"Parklaan", "Sportlaan", "Zwembadweg",
	},
	streetStems = {
		"Kerk", "Molen", "School", "Dorp", "Markt", "Haven",
		"Kade", "Sluis", "Brug", "Veer", "Dijk", "Duin",
		"Strand", "Heide", "Bos", "Berg", "Dal", "Beuken",
		"Eiken", "Linden", "Iepen", "Roos", "Tulp", "Merel",
		"Mees", "Zwaluw", "Fabriek", "Spoor", "Stations", "Boeren",
		"Akker", "Wei", "Hof", "Pastorie", "Raadhuis", "Kruis",
		"Zand", "Klei", "Veen", "Polder", "Water", "Visser",
		"Smid", "Bakker", "Brouwer", "Wever", "Zaag", "Kolen",
		"Mijn", "Gast", "Pol",
	},
	streetSuffixes = {
		"straat", "laan", "weg", "pad", "plein", "steeg",
		"hof", "kade", "singel", "gracht", "dijk", "wal",
		"park", "gaarde",
	},
	firstMale = {
		"Jan", "Piet", "Klaas", "Henk", "Kees", "Willem",
		"Johan", "Hendrik", "Cornelis", "Jacob", "Gerrit", "Dirk",
		"Pieter", "Adriaan", "Maarten", "Bram", "Daan", "Sem",
		"Lars", "Luuk", "Jesse", "Thijs", "Ruben", "Sander",
		"Stefan", "Marco", "Rob", "Peter", "Frank", "Erik",
		"Bas", "Joost", "Tim", "Niels", "Mark", "Martijn",
		"Jeroen", "Wouter", "Rick", "Tom", "Joris", "Floris",
		"Gijs", "Hidde", "Sjoerd", "Wim", "Gert", "Arie",
		"Teun", "Mees", "Finn", "Milan", "Noah", "Lucas",
		"Stijn", "Ties", "Wessel", "Jelle", "Koen", "Siem",
		"Thomas", "Max", "Hans", "Ton", "Cor", "Bert",
		"Joop", "Rinus", "Ab", "Evert", "Harm", "Jelmer",
		"Folkert", "Douwe", "Sietse", "Pim", "Ard", "Ronald",
	},
	firstFemale = {
		"Maria", "Johanna", "Anna", "Cornelia", "Wilhelmina", "Geertruida",
		"Elisabeth", "Petronella", "Catharina", "Hendrika", "Emma", "Sophie",
		"Julia", "Anna", "Lotte", "Fleur", "Eva", "Sanne",
		"Femke", "Lisa", "Iris", "Nina", "Mila", "Tess",
		"Noor", "Lieke", "Roos", "Anouk", "Maud", "Esmee",
		"Saar", "Sara", "Zoë", "Isa", "Merel", "Britt",
		"Demi", "Linda", "Marieke", "Petra", "Ingrid", "Annemarie",
		"Els", "Marijke", "Truus", "Riet", "Door", "Gerda",
		"Hanneke", "Jolanda", "Karin", "Mieke", "Yvonne", "Nicole",
		"Sandra", "Wendy", "Fenna", "Jildou", "Aafke", "Wietske",
		"Trijntje", "Sjoukje", "Tineke", "Bernadette", "Charlotte", "Lena",
		"Liv", "Olivia", "Lotte",
	},
	lastNames = {
		"de Jong", "Jansen", "de Vries", "van den Berg", "van Dijk", "Bakker",
		"Janssen", "Visser", "Smit", "Meijer", "de Boer", "Mulder",
		"de Groot", "Bos", "Vos", "Peters", "Hendriks", "van Leeuwen",
		"Dekker", "Brouwer", "de Wit", "Dijkstra", "Smits", "de Graaf",
		"van der Meer", "van der Linden", "Kok", "Jacobs", "de Haan", "Vermeulen",
		"van den Heuvel", "van der Veen", "van den Broek", "de Bruijn", "de Bruin", "van der Heijden",
		"Schouten", "van Beek", "Willems", "van Vliet", "van de Ven", "Hoekstra",
		"Maas", "Verhoeven", "Koster", "Prins", "Blom", "Huisman",
		"Peeters", "Kuipers", "van Dam", "van der Wal", "Postma", "Kramer",
		"Hermans", "Scholten", "Hoogland", "van Wijk", "Molenaar", "Boer",
		"Schipper", "Zwart", "de Ruiter", "Timmermans", "Smeets", "Hofman",
		"Bosman", "Wolters", "Veenstra", "de Lange", "Bouma", "Kamphuis",
		"van Es", "Kuiper", "Lammers", "Wiersma", "Bijl", "Ter Haar",
		"Ten Cate", "Van der Sluis", "Van Rijn", "Van Gogh", "De Haas", "De Ridder",
		"Van der Pol", "Oosterhuis",
	},
	cfg = {
		["streetExtra"] = 400,
		["lastNameFirst"] = false,
	},
	fallback = "kust",
}

local M = data_cfg

function M.pick(t)
	return t[math.random(1, #t)]
end

function M.shuffled(t)
	local s = {}
	for i = 1, #t do s[i] = t[i] end
	for i = #s, 2, -1 do
		local j = math.random(i)
		s[i], s[j] = s[j], s[i]
	end
	return s
end

-- Generates a name in a theme: stem + suffix, sometimes with a prefix.
function M.generate(theme)
	local g = M.gen[theme] or M.gen[M.fallback]
	if not g or #g.stems == 0 or #g.suffixes == 0 then return nil end
	local stem, suffix = M.pick(g.stems), M.pick(g.suffixes)
	for _ = 1, 10 do
		if stem:lower() ~= suffix then break end
		suffix = M.pick(g.suffixes)
	end
	local name = stem .. suffix
	if #M.prefixes > 0 and math.random() < g.prefixChance then
		name = M.pick(M.prefixes) .. name
	end
	return name
end

-- Picks an unused town name for a theme. used = set { [name] = true }.
function M.townName(theme, used)
	if not M.towns[theme] then theme = M.fallback end
	local pool = M.towns[theme]
	local g = M.gen[theme]
	local mode = g and g.mode or "both"

	local function fromCurated()
		if #pool == 0 then return nil end
		local start = math.random(1, #pool)
		for i = 0, #pool - 1 do
			local n = pool[((start + i - 1) % #pool) + 1]
			if not used[n] then return n end
		end
		return nil
	end
	local function fromGenerated()
		for _ = 1, 200 do
			local n = M.generate(theme)
			if n and not used[n] then return n end
		end
		return nil
	end

	local n
	if mode == "generated" then n = fromGenerated() or fromCurated()
	elseif mode == "curated" then n = fromCurated()
	else n = fromCurated() or fromGenerated() end

	if not n then
		local base = #pool > 0 and M.pick(pool) or theme
		local k = 2
		while used[base .. " " .. k] do k = k + 1 end
		n = base .. " " .. k
	end
	used[n] = true
	return n
end

function M.allTownThemes()
	local keys = {}
	for k in pairs(M.towns) do keys[#keys + 1] = k end
	table.sort(keys)
	return keys
end

return M
