
-- Game script: on the first tick, gives towns a name that fits their location.
-- The rules are in CFG below (generated by Names Studio).

local MOD_ID = "dutch_names_1"

local CFG = {
	["order"] = {
		"industry_close", "water", "industry_far", "hill", "rural",
	},
	["industryClose"] = 600,
	["industryFar"] = 1500,
	["waterNear"] = 1500,
	["waterMaxScan"] = 4000,
	["seaMin"] = 3000,
	["lakeMin"] = 400,
	["hillDelta"] = 15,
	["randomChance"] = 0.15,
	["seaTheme"] = "kust",
	["lakeTheme"] = "meer",
	["riverTheme"] = "rivier",
	["hillTheme"] = "heuvel",
	["rural"] = {
		{
			["theme"] = "landbouw",
			["weight"] = 2,
		},
		{
			["theme"] = "polder",
			["weight"] = 1,
		},
		{
			["theme"] = "bos",
			["weight"] = 1,
		},
	},
	["industryMap"] = {
		{
			["keywords"] = {
				"fishing", "platform",
			},
			["theme"] = "kust",
		},
		{
			["keywords"] = {
				"forest", "saw", "paper", "furniture",
			},
			["theme"] = "hout",
		},
		{
			["keywords"] = {
				"coal", "iron", "quarry", "sand", "clay", "dredg",
			},
			["theme"] = "mijn",
		},
		{
			["keywords"] = {
				"farm", "cotton", "rubber", "livestock",
			},
			["theme"] = "landbouw",
		},
	},
	["industryDefault"] = "industrie",
	["anyThemes"] = {
		"kust", "rivier", "heuvel", "industrie", "hout", "meer",
		"stad", "landbouw", "mijn", "bos", "polder",
	},
	["fallbackTheme"] = "kust",
}

local WATER_STEP = 50
local DIRECTIONS = 16

local function say(msg)
	print("[dutch_names] " .. tostring(msg))
end

local function vec(x, y)
	return api.type.Vec2f.new(x, y)
end

local function onWater(x, y)
	local p = vec(x, y)
	return api.engine.terrain.isValidCoordinate(p) and api.engine.terrain.isOnWater(p)
end

-- Nearest water (distance) and the width of that water, or nil.
local function scanWater(px, py)
	local bestDist, bestWidth
	for i = 0, DIRECTIONS - 1 do
		local a = 2 * math.pi * i / DIRECTIONS
		local dx, dy = math.cos(a), math.sin(a)
		local first
		for d = WATER_STEP, CFG.waterNear, WATER_STEP do
			if onWater(px + dx * d, py + dy * d) then first = d; break end
		end
		if first and (bestDist == nil or first < bestDist) then
			local d = first
			while d < CFG.waterMaxScan and onWater(px + dx * d, py + dy * d) do d = d + 100 end
			bestDist, bestWidth = first, d - first
		end
	end
	return bestDist, bestWidth
end

local function relativeHeight(px, py)
	local sum, n = 0, 0
	for i = 0, 7 do
		local a = 2 * math.pi * i / 8
		local p = vec(px + math.cos(a) * 800, py + math.sin(a) * 800)
		if api.engine.terrain.isValidCoordinate(p) then
			sum = sum + api.engine.terrain.getHeightAt(p)
			n = n + 1
		end
	end
	if n == 0 then return 0 end
	return api.engine.terrain.getHeightAt(vec(px, py)) - sum / n
end

local function industryTheme(fileName)
	local f = (fileName or ""):lower()
	for _, m in ipairs(CFG.industryMap) do
		for _, k in ipairs(m.keywords) do
			if f:find(k, 1, true) then return m.theme end
		end
	end
	return CFG.industryDefault
end

local function nearestIndustry(industries, px, py)
	local best, bestDist
	for _, ind in ipairs(industries) do
		local dx, dy = ind.pos.x - px, ind.pos.y - py
		local d = math.sqrt(dx * dx + dy * dy)
		if bestDist == nil or d < bestDist then best, bestDist = ind, d end
	end
	return best, bestDist
end

local function weightedPick(list)
	local total = 0
	for _, x in ipairs(list) do total = total + x.weight end
	if total <= 0 then return list[1] and list[1].theme end
	local r = math.random() * total
	for _, x in ipairs(list) do
		r = r - x.weight
		if r < 0 then return x.theme end
	end
	return list[#list].theme
end

local function classify(town, industries)
	local px, py = town.pos.x, town.pos.y
	local ind, indDist = nearestIndustry(industries, px, py)
	local wDist, wWidth, wDone
	for _, rule in ipairs(CFG.order) do
		if rule == "industry_close" then
			if ind and indDist <= CFG.industryClose then return industryTheme(ind.fileName), "industry close by" end
		elseif rule == "water" then
			if not wDone then wDist, wWidth = scanWater(px, py); wDone = true end
			if wDist then
				if wWidth >= CFG.seaMin then return CFG.seaTheme, "sea at " .. wDist .. " m" end
				if wWidth >= CFG.lakeMin then return CFG.lakeTheme, "lake at " .. wDist .. " m" end
				return CFG.riverTheme, "river at " .. wDist .. " m"
			end
		elseif rule == "industry_far" then
			if ind and indDist <= CFG.industryFar then return industryTheme(ind.fileName), "industry nearby" end
		elseif rule == "hill" then
			if relativeHeight(px, py) > CFG.hillDelta then return CFG.hillTheme, "above surroundings" end
		elseif rule == "rural" then
			local t = weightedPick(CFG.rural)
			if t then return t, "flat land" end
		end
	end
	return CFG.fallbackTheme, "no rule applied"
end

local function run()
	local d = require(MOD_ID .. "::/names/dutch_data.lua")
	local map = api.engine.terrain.makeMapFromGame(false, true, true, false)
	local towns, industries = map.towns or {}, map.industries or {}
	say(#towns .. " towns and " .. #industries .. " industries found")

	local used = {}
	for _, t in ipairs(towns) do
		if t.name then used[t.name] = true end
	end

	for _, t in ipairs(towns) do
		if t.existing then
			local theme, reason = classify(t, industries)
			if #CFG.anyThemes > 0 and math.random() < CFG.randomChance then
				theme, reason = CFG.anyThemes[math.random(#CFG.anyThemes)], "random theme"
			end
			local name = d.townName(theme, used)
			say(tostring(t.name) .. " -> " .. name .. " (" .. theme .. ", " .. reason .. ")")
			api.cmd.sendCommand(api.cmd.makeEntitySetNameCmd(t.existing, name))
		end
	end
end

function data()
	return {
		update = function(userParams, state, dt)
			if dt == 0 then return end
			local s = state:get()
			if s and s.done then return end
			state:set({ done = true })
			local ok, err = pcall(run)
			if not ok then say("FOUT: " .. tostring(err)) end
		end,
	}
end
